### ISSUE TITLE
Request: TTF font format

### ISSUE THREAD

**Issue by nagyrobi** [mampfes/ha-knx-uf-iconset#4]
Is there a way to convert/release this package in a TTF font file, just like MDI icons are? This would allow us to use them easily in [openHASP](https://haswitchplate.github.io/openHASP-docs/).

**Comment by mampfes** [comment]
Sorry, I am not aware of such a possibility. The icons are available as SVG and PNG:
https://github.com/OpenAutomationProject/knx-uf-iconset

**Comment by nagyrobi** [comment]
Some kind of script would be nice which could be hooked into Github's actions menu and would generate the TTF automatically whenever you commit a new change :)

Maybe like https://github.com/Templarian/MaterialDesign-Font-Build or 
https://mediatemple.net/blog/design-creative/creating-implementing-icon-font-tutorial/

**Comment by nagyrobi** [comment]
https://github.com/nagyrobi/knx-uf-iconset-to-ttf
